### ISSUE TITLE
Editing Boot Menu

### ISSUE THREAD

**Issue by SomeMuthaFunky** [morbitzer/linux-luks-tpm-boot#11]
Hi, I'm having problems with edits to the boot menu still allowing the machine to boot.

As per the following segment:
"Checking if it works
If you now reboot again, your system shouldn't boot up when you edit for example the boot menu entries. Just give it a try, press E in the TrustedGRUB2 boot menu. Then edit for example one of the echo lines, to output something different. Then press F10 to boot. This should be enough for your TPM to refuse to give out the key!
It works? Perfect, you are ready to go! Enjoy having to type one password less during boot time! :)

The system still boots up, although it shouldn't? Have a look at the next step…

Setting the nvLocked bit
On one of my test systems, I had the problem that the secret stored in the NVRAM could be read even when the PCRs it was sealed to had changed. It took me quite a long time to figure out what went wrong: Apparently, the TPM manufacturer didn't set the nvLocked bit, which means that reading the NVRAM was always possible, no matter if you sealed it to some PCRs or assigned a password to it. Thanks to this discussion at the TrouSers mailing list, I was finally able to figure out what to do:

You'll have to define an area the size 0 at position 0xFFFFFFF in the NVRAM. This will equal setting the nvLocked bit. You can do so with the following command:

sudo tpm_nvdefine -i 0xFFFFFFFF –size=0

This solved the problem for me. Afterwards, my sealed NVRAM areas couldn't be read anymore if the PCRs it was sealed to had changed, and my system was finally save again. "

If I try this (sudo tpm_nvdefine -i 0xFFFFFFFF –size=0) I just get an error that the value needs to be a positive integer. 
My next question is regarding this statement "I had the problem that the secret stored in the NVRAM could be read even when the PCRs it was sealed to had changed." The guide doesn't mention how to seal to specific PCR's or have I missed that? Please forgive my lack of knowledge on this subject, it's why I'm referring to a guide.

**Comment by morbitzer** [comment]
To figure out what PCR changes when you modify something, you can first read the PCRs in the normal state with `cat /sys/class/tpm/tpm0/device/pcrs`. 
Afterwards, reboot the system, and modify something in the boot process, for example your GRUB. Once boot up, do again a `cat /sys/class/tpm/tpm0/device/pcrs` and check if you can see a difference.

**Comment by SomeMuthaFunky** [comment]
Will do, thanks for your help on the matter.

**Comment by SomeMuthaFunky** [comment]
Hi, I've gone through this from scratch and as part of the process did as you suggested above. It is PCR11 that is changed when I edit the GRUB at boot but this is not picked up at all after sealing. Having read the script PCR11 should be sealed if not using the -z option. I have no idea why it is still allowed to boot. Any thoughts?

**Comment by morbitzer** [comment]
I guess it's similar to the problem that I had with my TPM, so the nvLocked bit might not be set. 
You'll have to look up how this can be done with your TPM.
