### ISSUE TITLE
License? 

### ISSUE THREAD

**Issue by noahbliss** [morbitzer/linux-luks-tpm-boot#12]
I'd like to rip off some of your scripts for my [mortar](https://github.com/noahbliss/mortar) project and wanted to know what license you use for your work here. For files that I base my own on/take heavy inspiration from, I include a comment near the top stating so and including a link to the original file location. Is this sufficient?

No is fine. I can rewrite the functionality if you'd rather keep your work here.

**Comment by morbitzer** [comment]
To be honest, I never thought about a license or anything. Your project looks cool, so go ahead and use whatever you need. Mentioning the original source is of course appreciated :)

**Comment by noahbliss** [comment]
Thanks! Feel free to send issues/PRs!
