### ISSUE TITLE
tpm-hook

### ISSUE THREAD

**Issue by SomeMuthaFunky** [morbitzer/linux-luks-tpm-boot#2]
I have been following this guide but am having problems right at the end with the script tpm-hook. I keep getting errors expecting "in" Line 7 at the start of the case statement. If I comment out that whole section then I get an error
/usr/sbin/mkinitramfs: 699: /usr/sbin/mkinitramfs: /etc/initramfs-tools/hooks/tpm-hook: not found yet it is there.

**Comment by morbitzer** [comment]
So you get the error during the ``sudo update-initramfs -u''?
Which distribution are you using?
