### ISSUE TITLE
Bug/typo in seal-nvram.sh

### ISSUE THREAD

**Issue by stengoes** [morbitzer/linux-luks-tpm-boot#3]
Got the following error:
```
/sbin/seal-nvram.sh: line 22: read: `Owner password: ': not a valid identifier
```
while running:
```bash
$ sudo /sbin/seal-nvram.sh -z
```

I think this is fixed by reordering the parameters:
```
read -s -r -p "Owner password: " OWNERPW
```
Instead of:
```
read -s -p -r "Owner password: " OWNERPW
```

**Comment by morbitzer** [comment]
Interesting, it did work for me. 
Anyway, I commited the change - hopefully it works for everyone now!
