### ISSUE TITLE
Defective By Design?

### ISSUE THREAD

**Issue by Mis012** [morbitzer/linux-luks-tpm-boot#5]
Hi,
It may be that the documentation wasn't clear enough to me, but doesn't this share DRM's defective by design nature? If I understand it correctly, the machine will decrypt itself as long as I don't change the bootloader etc.? Because for one, the key must therefore be there and I'm sure it's technically possible to get it out if you're NSA or so, and if you're not maybe you can somehow get the data after the decryption has happened? Also 100% possible if I understand this correctly, and although it may not be *easy*, you can also have 100% impossible if you keep the keys somewhere safe (or at least encrypt them with a password...)

**Comment by SuperSandro2000** [comment]
No, it isn't.
If it decrypt itself you are making it secure against disassembly and can encrypt your drive more securely than hardcoding or putting the key somewhere else.
If you auto decrypt your drive you can easily extract the key. If you protect it with a password that is secure it gets a bit harder.
As long as the drive is decrypted you can just copy everything over but as soon as you unpower the machine and set a boot password you are making it a bit more of a headache to get your data.
There is no 100% safe. You are just delaying the decryption long enough to be safe or to make them give up on it. If the agency would need to spend a lot of money to get your data and they don't have enough evidence they might not do it. If your data is unencrypted they have evidence right away.
A simple passwordless approach just protects against the average lurking into your stuff.
And final note: as soon as some one has physical access to your machine you need to think that your data is compromised eventually and you should change every password or key that was on it.

**Comment by morbitzer** [comment]
Thanks @SuperSandro2000 for the great answer!
