### ISSUE TITLE
Would there be an easy way to make this work with TPM 2?

### ISSUE THREAD

**Issue by stengoes** [morbitzer/linux-luks-tpm-boot#7]
I would like to adapt your approach to make it work with TPM 2. Do you think this will be easy? Do you have some ideas to point me in the right direction?

I already noticed that trousers is not working with TPM 1.2, so I will definitely need to find an alternative for that.

**Comment by morbitzer** [comment]
[This website](https://blog.dowhile0.org/2017/10/18/automatic-luks-volumes-unlocking-using-a-tpm2-chip/) describes how to do the same with a TPM2.

I did not try it yet, but I would be happy to know if it works for you. If so, I can put the link directly in the README.md

**Comment by stengoes** [comment]
Thanks for your swift reply. 

I look at your suggestion which looks really easy, but I found out that clevis is not supported on ubuntu 16.04. 

So I looked a bit further and found [this  website](https://threat.tevora.com/secure-boot-tpm-2/). Where they setup a UEFI secure boot in combination with automatic disk decryption using TPM 2. I will skip the UEFI secure boot for now and only follow their procedure for setting up the TPM 2 disk decryption. Their method seems to be pretty similar to your procedure which helps. So I will try it out in the next few days.

**Comment by stengoes** [comment]
So after some trying I managed to get it working!

First step: install tpm2-tools and all its depedencies.
```bash
# Install dependencies
sudo apt-get update && sudo apt-get -y install autoconf autoconf-archive automake libtool pkg-config gcc libssl-dev libcurl4-gnutls-dev doxygen

# Install tpm2-tss
git clone https://github.com/tpm2-software/tpm2-tss.git
cd tpm2-tss
git checkout e05d28ec  # I used this particular commit
./bootstrap
./configure --prefix=/usr
make -j5
sudo make install

# Install tpm2-tools
git clone https://github.com/tpm2-software/tpm2-tools.git
cd tpm2-tools
git checkout 446b4f37 # I used this particular commit
 ./bootstrap
 ./configure --prefix=/usr
 make -j5
 sudo make install
```

Second step: create a secret key and add it to the cryptsetup.
```bash
# Create secret and add to cryptsetup
sudo dd if=/dev/urandom of=/secret.bin bs=32 count=1
sudo chmod 700 /secret.bin
sudo cryptsetup luksAddKey /dev/sda3 /secret.bin
```

Third step: load the secret key into the TPM and make it persistent.
```bash
# Enable and clear yoru tpm in your BIOS first to start with a clean TPM

# Create primary TPM object
sudo tpm2_createprimary -c primary.ctx

# Create PCR Policy against PCR 0-7 
sudo tpm2_createpolicy --policy-pcr -l sha1:0,1,2,3,4,5,6,7 -L policy.digest 

# Create tpm object
sudo tpm2_create -C primary.ctx -u obj.pub -r obj.priv -L policy.digest -a "noda|adminwithpolicy|fixedparent|fixedtpm" -i /secret.bin

# Flush transient handles (making some room in the memory for the TPM)
sudo tpm2_flushcontext -t

# Load object into the TPM
sudo tpm2_load -C primary.ctx -u obj.pub -r obj.priv -c load.ctx

# Make object persistent
sudo tpm2_evictcontrol -c load.ctx

# Flush transient handles
sudo tpm2_flushcontext -t

# List persistent handles
sudo tpm2_getcap handles-persistent
# This command will output a list of persistent handles which can be used to unseal objects from the tpm
```

Command for unsealing and removing objects from the TPM 2.0:
```bash
sudo tpm2_unseal -c 0x81000000 -p pcr:sha1:0,1,2,3,4,5,6,7

# To remove a specific persistent handle from the TPM2.0 use:
#sudo tpm2_evictcontrol -c 0x81000000

```
